module.exports = [
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    courseId: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
