module.exports = [
  {
    id: 1,
    no: 1,
    name: "Pendahuluan",
    courseId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    no: 2,
    name: "Memulai Frontend",
    courseId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    no: 1,
    name: "Pendahuluan",
    courseId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    no: 2,
    name: "Memulai UI/UX design",
    courseId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    no: 1,
    name: "Pendahuluan",
    courseId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    no: 2,
    name: "Memulai bahasa assembly x86",
    courseId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    no: 3,
    name: "Membuat aplikasi android menggunakan asembly x86",
    courseId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    no: 1,
    name: "Pendahuluan",
    courseId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    no: 2,
    name: "Membuat Restful API dengan C",
    courseId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    no: 1,
    name: "Pendahuluan",
    courseId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 11,
    no: 2,
    name: "Memulai Backend dengan Golang",
    courseId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 12,
    no: 1,
    name: "Pendahuluan",
    courseId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    no: 2,
    name: "Memulai Android Studio",
    courseId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 14,
    no: 1,
    name: "Pendahuluan",
    courseId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 15,
    no: 2,
    name: "Memulai UI/UX design",
    courseId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 16,
    no: 1,
    name: "Pendahuluan",
    courseId: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 17,
    no: 2,
    name: "Memulai UI/UX design",
    courseId: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 18,
    no: 1,
    name: "Pendahuluan",
    courseId: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 19,
    no: 2,
    name: "Memulai Product Management",
    courseId: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 20,
    no: 1,
    name: "Pendahuluan",
    courseId: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 21,
    no: 2,
    name: "Memulai iOS dengan Swift",
    courseId: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 22,
    no: 1,
    name: "Pendahuluan",
    courseId: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 23,
    no: 2,
    name: "Memulai Data Science",
    courseId: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 24,
    no: 1,
    name: "Pendahuluan",
    courseId: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 25,
    no: 2,
    name: "Memulai Android dengan Android Studio",
    courseId: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
