module.exports = [
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Memulai Frontend",
    courseId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Memulai UI/UX design",
    courseId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Memulai bahasa assembly x86",
    courseId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 3,
    name: "Membuat aplikasi android menggunakan asembly x86",
    courseId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Membuat Restful API dengan C",
    courseId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Memulai Backend dengan Golang",
    courseId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Memulai Android Studio",
    courseId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Memulai UI/UX design",
    courseId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Memulai UI/UX design",
    courseId: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Memulai Product Management",
    courseId: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Memulai iOS dengan Swift",
    courseId: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Memulai Data Science",
    courseId: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 1,
    name: "Pendahuluan",
    courseId: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    no: 2,
    name: "Memulai Android dengan Android Studio",
    courseId: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
