module.exports = [
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 1,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 1,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 1,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 2,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 2,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 6",
    no: 6,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 2,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 7",
    no: 7,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 2,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 3,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 3,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 3,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 4,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 4,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 6",
    no: 6,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 4,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 5,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 5,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 5,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 6,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 6,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 6",
    no: 6,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 6,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 7",
    no: 7,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 7,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 8",
    no: 8,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 7,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 9",
    no: 9,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 7,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 8,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 8,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 8,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 9,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 9,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 6",
    no: 6,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 9,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 10,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 10,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 11,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 11,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 11,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 12,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 12,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 13,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 13,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 13,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 14,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 14,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 15,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 15,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 15,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 16,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 16,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 17,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 17,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 17,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 18,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 18,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 19,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 19,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 19,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 20,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 20,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 21,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 21,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 21,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 22,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 22,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 23,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 23,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 23,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 1",
    no: 1,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 24,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 2",
    no: 2,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 24,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 3",
    no: 3,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 25,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 4",
    no: 4,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 25,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "video 5",
    no: 5,
    videoUrl: "https://youtu.be/ixOd42SEUF0",
    chapterId: 25,
    duration: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
